# -*- coding: utf-8 -*-
"""og_Kerry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KODtPtO2DG1uJNmByplhcW-0xl9CLxmd
"""

#อันนี้นะ
import datetime
def input_box():
  print('กรุณาเลือกพื้นที่ ที่ท่านต้องการส่ง\nกด 1 เพื่อส่งในกรุงเทพและปริมลฑล\nกด 2 เพื่อส่งในเขตต่างจงหวัด')
  for i in range(num):
    print('กล่องที่', i+1 )
    print('==========')
    while True:
      while True:
        add[i] = int(input('โปรดเลือกพื้นที่การส่ง'))
        if add[i] == 1 or add[i] == 2:
          break
        else:
          print('คุณใส่ที่อยู่ผิด กรุณาใส่ใหม่')
          continue
      while True:
        print('==========')
        print(' ขนาดกล่องจะมีทั้งหมด 5 แบบ ดังนี้ s m l xl xxl')
        size[i] = input('ใส่ขนาดกล่อง:').strip()
        if size[i] == 's' or size[i] == 'm' or size[i] == 'l' or size[i] == 'xl' or size[i] == 'xxl':
          break
        else:
          print('คุณใส่ขนาดกล่องผิดกรุณาใส่ใหม่่')
          continue
      while True:
        print('==========')
        weight[i] = float(input('ใส่น้ำหนักของกล่อง(kg):'))
        if weight[i] <=0 :
          print('คุณใส่น้ำหนักผิด กรุณาตรวจสอบแล้วใส่ใหม่')
          continue
        else:
          break
      print('==========')
      name[i] = str(input('ใส่ชื่อผู้รับ')).strip()
      break

def cal_weight():
  for i in range(num):
    if add[i] == 1:

      while True:
        if size[i] == 's':
          if weight[i] <= 7:
            total[i] = 65+10
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
        if size[i] == 'm':
          if weight[i] <= 10:
            total[i] = 90+20
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue
        if size[i] == 'l':
          if weight[i] <= 15:
            total[i] = 185+30
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue
        if size[i] == 'xl':
          if weight[i] <= 20:
            total[i] = 290
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue
        if size[i] == 'xxl':
          if weight[i] <= 25:
            total[i] = 380
            break
          else:
            print('กล่องที่',i+1,'น้ำหนักเยอะกว่าปกติ\n**หากต้องการส่ง ค่าบริการ จะเท่ากับ 500 บาท**\nหากต้องการส่งราคานี้ กด 1 \nหากไม่ต้องการใช้บริการแล้ว กด 2')
            check = int(input())
            if check == 1:
              total[i] = 500
              break
            elif check == 2:
              add[i] = '-'
              size[i] = '-'
              weight[i] = '-'
              name[i] = '-'
              break

    
    if add[i] == 2:
      while True:
        if size[i] == 's':
          if weight[i] <= 7:
            total[i] = 80
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue

        if size[i] == 'm':
          if weight[i] <= 10 :
            total[i] = 100
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue

        if size[i] == 'l':
          if weight[i] <= 15:
            total[i] = 205
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue

        if size[i] == 'xl':
          if weight[i] <= 20:
            total[i] = 330
            break
          else:
            print('กล่องที่',i+1,'กรุณาเปลี่ยนกล่องใหม่ คุณใส่น้ำหนักเกิน')
            size[i] = input().strip()
            continue

        if size[i] == 'xxl':
          if weight[i] <= 25:
            total[i] = 420
            break
          else:
            print('กล่องที่',i+1,'น้ำหนักเยอะกว่าปกติ\n**หากต้องการส่ง ค่าบริการ จะเท่ากับ 500 บาท**\nหากต้องการส่งราคานี้ กด 1 \nหากไม่ต้องการใช้บริการแล้ว กด 2')
            check = int(input())
            if check == 1:
              total[i] = 500
              break
            elif check == 2:
              add[i] = '-'
              size[i] = '-'
              weight[i] = '-'
              name[i] = '-'
              break

def discount():
  dis = input('กรุณาใส่โค่ดส่วนลด(ถ้ามี)').strip()
  if dis =='programming1':
    sum_dis = sum_ship*0.05
    if num >=3 and num < 6:
      sum_dis = (sum_ship*0.05)+sum_dis
    elif num >= 6 and num<10:
      sum_dis = (sum_ship*0.10)+sum_dis
    elif num >=10:
      sum_dis = (sum_ship*0.15)+sum_dis
  else:
    if num >=3 and num < 6:
      sum_dis = sum_ship*0.05
    elif num >= 6 and num<10:
      sum_dis = sum_ship*0.10
    elif num >=10:
      sum_dis = sum_ship*0.15
def print_list():
  for i in range(num):
    print(i+1,'.',' เลขพัสดุ :','TPK'+x.strftime("%Y%m%d%S")+'{}'.format(i))
    print('   ชื่อผู้รับ: ',name[i])
    print('   ขนากล่อง size                          ',size[i])
    print('    น้ำหนัก                                ',weight[i],'Kg')
    print('ค่าส่ง/1 กล่อง                               ',total[i],'บาท')

def print_price():
  print('รวม                                        ',sum_ship,'บาท')
  print('ส่วนลด                                      ',sum_dis,'บาท')
  print('VAT 7%                                     ',round(vat,2),'บาท')
  print('ราคาสุทธิ                                    ',round((sum_ship-sum_dis)+vat,2),'บาท')
'''def heart():
  for i in range(6):
    for j in range(7):
      if (i == 0 and j %3 != 0) or (i == 1 and j%3 == 0) or (i-j == 2) or (i+j == 8):
        print('*',end=' ')
      else:
        print(' ',end=' ')
    print()'''
###main###
num = int(input('กรุณาใส่จำนวนกล่องที่คุณต้องการส่ง'))
size = ['']*num
name = ['']*num
weight = [0]*num
add = [0]*num
total = [0]*num
#input
x = datetime.datetime.now()
name_pc = input('กรุณาใส่ชื่อผู้ส่ง').strip()
numbox = input_box()
bankok = add.count(1)
upcun = add.count(2)
sum_dis=0
cal_weight()
sum_ship = sum(total)
dis = input('กรุณาใส่โค่ดส่วนลด(ถ้ามี)').strip()
if dis =='programming1':
  sum_dis = sum_ship*0.05
  if num >=3 and num < 6:
    sum_dis = (sum_ship*0.05)+sum_dis
  elif num >= 6 and num<10:
    sum_dis = (sum_ship*0.10)+sum_dis
  elif num >=10:
    sum_dis = (sum_ship*0.15)+sum_dis
else:
  if num >=3 and num < 6:
    sum_dis = sum_ship*0.05
  elif num >= 6 and num<10:
    sum_dis = sum_ship*0.10
  elif num >=10:
    sum_dis = sum_ship*0.15

vat = sum_ship*0.07
print('----------------------------------------------------------')
print('               TPK DEVELOPER INTERNATIONAL                ')
print('  ผู้ส่งชื่อ : ',name_pc)
print('  เลขที่ใบเสร็จ : ',x.strftime("%Y%m%d%S"))
print('----------------------------------------------------------')
print('จำนวนกล่องที่จัดส่งภายในเขตกรุงเทพ                ',bankok,' กล่อง')
print('จำนวนกล่องที่จัดส่งในเขตต่างจังหวัด                 ',upcun,' กล่อง')
print('----------------------------------------------------------')
print_list()
print('==========================================================')
print_price()
print()
print('--------ขอบคุณที่ใช้บริการ TPK Developer international---------')